/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "outline": "#727974",
        "on-tertiary-container": "#7a93aa",
        "on-primary-fixed-variant": "#2e4d40",
        "on-primary": "#ffffff",
        "on-tertiary-fixed-variant": "#31495e",
        "surface-container-lowest": "#ffffff",
        "on-secondary-fixed-variant": "#3f4c00",
        "secondary-fixed-dim": "#b7d248",
        "primary-fixed-dim": "#accebe",
        "outline-variant": "#c1c8c3",
        "surface-container": "#eeeef0",
        "on-surface-variant": "#414844",
        "background": "#f9f9fc",
        "on-secondary-fixed": "#171e00",
        "on-background": "#1a1c1e",
        "on-tertiary": "#ffffff",
        "primary-container": "#0f2e23",
        "surface-variant": "#e2e2e5",
        "secondary": "#546500",
        "surface-dim": "#dadadc",
        "primary-fixed": "#c8ead9",
        "on-secondary": "#ffffff",
        "error-container": "#ffdad6",
        "on-error": "#ffffff",
        "error": "#ba1a1a",
        "surface": "#f9f9fc",
        "on-tertiary-fixed": "#011d31",
        "surface-tint": "#466557",
        "inverse-surface": "#2f3133",
        "on-error-container": "#93000a",
        "primary": "#001810",
        "surface-container-highest": "#e2e2e5",
        "inverse-on-surface": "#f0f0f3",
        "on-surface": "#1a1c1e",
        "tertiary-fixed-dim": "#b0c9e3",
        "tertiary-fixed": "#cce5ff",
        "inverse-primary": "#accebe",
        "on-secondary-container": "#596c00",
        "surface-container-low": "#f3f3f6",
        "surface-bright": "#f9f9fc",
        "on-primary-container": "#779788",
        "secondary-container": "#d2ef61",
        "surface-container-high": "#e8e8ea",
        "tertiary": "#001626",
        "secondary-fixed": "#d2ef61",
        "on-primary-fixed": "#012016",
        "tertiary-container": "#112b3f"
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem"
      },
      spacing: {
        "base": "8px",
        "margin-mobile": "16px",
        "gutter": "24px",
        "margin-desktop": "40px",
        "xs": "4px",
        "sm": "12px",
        "xl": "80px",
        "md": "24px",
        "lg": "48px"
      },
      fontFamily: {
        "headline-lg": ["Inter"],
        "body-md": ["Inter"],
        "headline-lg-mobile": ["Inter"],
        "body-lg": ["Inter"],
        "label-sm": ["Inter"],
        "body-sm": ["Inter"],
        "label-md": ["Inter"],
        "headline-xl": ["Inter"],
        "headline-md": ["Inter"]
      },
      fontSize: {
        "headline-lg": ["32px", { lineHeight: "40px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "headline-lg-mobile": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "label-sm": ["12px", { lineHeight: "14px", fontWeight: "500" }],
        "body-sm": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "label-md": ["14px", { lineHeight: "16px", letterSpacing: "0.05em", fontWeight: "600" }],
        "headline-xl": ["48px", { lineHeight: "56px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "headline-md": ["24px", { lineHeight: "32px", fontWeight: "600" }]
      }
    },
  },
  plugins: [],
}
